#!/usr/bin/env bash
#
# Fleet manager — operate many clinics on one server.
#
# Every clinic is a self-contained folder under clinics/<slug>/ with its own
# config, database, Meta credentials and systemd service. Nothing is shared
# between clinics except the Python virtualenv and the code itself.
#
#   sudo clinic-fleet add smile-dental
#   sudo clinic-fleet list
#   sudo clinic-fleet backup all
#   sudo clinic-fleet deploy
#
# Installed to /usr/local/bin/clinic-fleet by install_server.sh.

set -euo pipefail

APP_DIR="${APP_DIR:-/opt/clinic-bot}"
CLINICS_DIR="${APP_DIR}/clinics"
CADDY_DIR="/etc/caddy/clinics.d"
FLEET_CONF="${APP_DIR}/fleet.conf"
APP_USER="clinicbot"
PORT_BASE=8001
RETAIN_DAYS="${RETAIN_DAYS:-30}"

# shellcheck disable=SC1090
[[ -f "$FLEET_CONF" ]] && source "$FLEET_CONF"
DOMAIN="${DOMAIN:-}"

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
ok()    { printf '\033[1;32m✓\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m!\033[0m %s\n' "$*"; }
die()   { printf '\033[1;31m✗\033[0m %s\n' "$*" >&2; exit 1; }

need_root() { [[ $EUID -eq 0 ]] || die "This command needs sudo."; }

valid_slug() {
    [[ "$1" =~ ^[a-z0-9][a-z0-9-]{1,30}[a-z0-9]$ ]] \
        || die "Invalid slug '$1'. Use lowercase letters, digits and hyphens (3-32 chars)."
}

clinic_dir() { echo "${CLINICS_DIR}/$1"; }

exists() { [[ -d "$(clinic_dir "$1")" ]]; }

all_slugs() {
    [[ -d "$CLINICS_DIR" ]] || return 0
    find "$CLINICS_DIR" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null | sort
}

clinic_port() {
    local env_file
    env_file="$(clinic_dir "$1")/.env"
    [[ -f "$env_file" ]] || return 0
    grep -E '^PORT=' "$env_file" | head -1 | cut -d= -f2
}

next_port() {
    local used highest=$((PORT_BASE - 1))
    for slug in $(all_slugs); do
        used="$(clinic_port "$slug")"
        [[ -n "$used" && "$used" -gt "$highest" ]] && highest="$used"
    done
    echo $((highest + 1))
}

# ---------------------------------------------------------------------------
cmd_add() {
    need_root
    local slug="${1:-}"
    [[ -n "$slug" ]] || die "Usage: clinic-fleet add <slug>"
    valid_slug "$slug"
    exists "$slug" && die "Clinic '$slug' already exists. Use 'reconfigure' to change it."
    [[ -n "$DOMAIN" ]] || die "DOMAIN is not set in ${FLEET_CONF}. Add: DOMAIN=bot.example.duckdns.org"

    local dir port token
    dir="$(clinic_dir "$slug")"
    port="$(next_port)"
    token="$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"

    bold "Creating clinic '${slug}' on port ${port}"
    mkdir -p "${dir}/data"

    cp "${APP_DIR}/config/clinic.yaml" "${dir}/clinic.yaml"

    cat >"${dir}/.env" <<EOF
# Clinic: ${slug}
# Generated by clinic-fleet on $(date -Iseconds)
# Fill in the Meta credentials below, then: clinic-fleet start ${slug}

PORT=${port}
PUBLIC_BASE_URL=https://${DOMAIN}/c/${slug}

CLINIC_CONFIG_PATH=clinic.yaml
DATABASE_URL=sqlite:///data/clinic.db
LOG_LEVEL=INFO

# --- Meta WhatsApp Cloud API (unique per clinic) ---
WHATSAPP_PHONE_NUMBER_ID=
WHATSAPP_BUSINESS_ACCOUNT_ID=
WHATSAPP_ACCESS_TOKEN=
WHATSAPP_APP_SECRET=
WHATSAPP_VERIFY_TOKEN=${token}
WHATSAPP_API_VERSION=v21.0
EOF

    # Path-based routing: one certificate, no wildcard DNS. handle_path strips
    # the /c/<slug> prefix, so the app never needs to know it is behind one.
    mkdir -p "$CADDY_DIR"
    cat >"${CADDY_DIR}/${slug}.caddy" <<EOF
handle_path /c/${slug}/* {
	reverse_proxy 127.0.0.1:${port}
}
EOF

    chown -R "${APP_USER}:${APP_USER}" "$dir"
    chmod 600 "${dir}/.env"
    chmod 750 "${dir}/data"

    systemctl reload caddy 2>/dev/null || warn "Could not reload Caddy — do it manually."

    ok "Clinic '${slug}' created."
    cat <<EOF

  Next steps:

    1. Edit this clinic's details (services, doctors, fees, UPI):
         sudo -u ${APP_USER} nano ${dir}/clinic.yaml

    2. Add the Meta credentials for THIS clinic's WhatsApp number:
         sudo nano ${dir}/.env

    3. Start it:
         sudo clinic-fleet start ${slug}

  Give Meta this webhook configuration:

    Callback URL:  https://${DOMAIN}/c/${slug}/webhook
    Verify token:  ${token}

EOF
}

# ---------------------------------------------------------------------------
cmd_remove() {
    need_root
    local slug="${1:-}"
    [[ -n "$slug" ]] || die "Usage: clinic-fleet remove <slug>"
    exists "$slug" || die "No such clinic: ${slug}"

    local dir archive
    dir="$(clinic_dir "$slug")"
    archive="${APP_DIR}/data/removed/${slug}-$(date +%Y%m%d-%H%M%S).tar.gz"

    warn "This will stop and remove clinic '${slug}'."
    read -rp "Type the clinic slug to confirm: " confirm
    [[ "$confirm" == "$slug" ]] || die "Aborted."

    systemctl disable --now "clinic-bot@${slug}" 2>/dev/null || true

    # Never delete patient data outright — archive it. A clinic that leaves and
    # comes back, or a mistaken removal, must be recoverable.
    mkdir -p "$(dirname "$archive")"
    tar -czf "$archive" -C "$CLINICS_DIR" "$slug"
    rm -rf "$dir"
    rm -f "${CADDY_DIR}/${slug}.caddy"
    systemctl reload caddy 2>/dev/null || true

    ok "Removed '${slug}'. Data archived to ${archive}"
}

# ---------------------------------------------------------------------------
cmd_list() {
    local slugs
    slugs="$(all_slugs)"
    [[ -n "$slugs" ]] || { echo "No clinics configured yet. Add one: clinic-fleet add <slug>"; return; }

    printf '%-24s %-6s %-10s %-8s %s\n' "CLINIC" "PORT" "STATE" "HEALTH" "WEBHOOK URL"
    printf '%.0s-' {1..100}; echo

    local port state health url
    for slug in $slugs; do
        port="$(clinic_port "$slug")"
        state="$(systemctl is-active "clinic-bot@${slug}" 2>/dev/null || echo unknown)"
        if [[ "$state" == "active" ]] && curl -fsS --max-time 3 "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
            health="ok"
        elif [[ "$state" == "active" ]]; then
            health="degraded"
        else
            health="-"
        fi
        url="https://${DOMAIN:-<domain>}/c/${slug}/webhook"
        printf '%-24s %-6s %-10s %-8s %s\n' "$slug" "${port:-?}" "$state" "$health" "$url"
    done
}

# ---------------------------------------------------------------------------
cmd_service() {
    need_root
    local action="$1" target="${2:-}"
    [[ -n "$target" ]] || die "Usage: clinic-fleet ${action} <slug|all>"

    if [[ "$target" == "all" ]]; then
        for slug in $(all_slugs); do
            if systemctl "$action" "clinic-bot@${slug}"; then
                ok "${action} ${slug}"
            else
                warn "${action} failed: ${slug}"
            fi
        done
    else
        exists "$target" || die "No such clinic: ${target}"
        if [[ "$action" == "start" ]]; then
            systemctl enable "clinic-bot@${target}" >/dev/null 2>&1 || true
        fi
        systemctl "$action" "clinic-bot@${target}"
        ok "${action} ${target}"
    fi
}

# ---------------------------------------------------------------------------
cmd_logs() {
    local slug="${1:-}"
    [[ -n "$slug" ]] || die "Usage: clinic-fleet logs <slug>"
    exec journalctl -u "clinic-bot@${slug}" -f -n 100
}

# ---------------------------------------------------------------------------
cmd_backup() {
    local target="${1:-all}" slugs
    if [[ "$target" == "all" ]]; then slugs="$(all_slugs)"; else
        exists "$target" || die "No such clinic: ${target}"
        slugs="$target"
    fi

    local db backup_dir stamp out
    stamp="$(date +%Y%m%d-%H%M%S)"
    for slug in $slugs; do
        db="$(clinic_dir "$slug")/data/clinic.db"
        [[ -f "$db" ]] || { warn "${slug}: no database yet, skipping"; continue; }

        backup_dir="${APP_DIR}/data/backups/${slug}"
        mkdir -p "$backup_dir"
        out="${backup_dir}/${slug}-${stamp}.db"

        # .backup takes a consistent snapshot even while the bot is writing;
        # a plain cp does not guarantee that.
        sqlite3 "$db" ".backup '${out}'"

        # A backup nobody verified is not a backup.
        if ! sqlite3 "$out" "PRAGMA integrity_check;" | grep -q '^ok$'; then
            rm -f "$out"
            warn "${slug}: INTEGRITY CHECK FAILED — backup discarded"
            continue
        fi

        gzip -f "$out"
        find "$backup_dir" -name '*.db.gz' -mtime "+${RETAIN_DAYS}" -delete
        ok "${slug}: backed up ($(find "$backup_dir" -name '*.db.gz' | wc -l) retained)"
    done
}

# ---------------------------------------------------------------------------
cmd_restore() {
    need_root
    local slug="${1:-}" archive="${2:-}"
    [[ -n "$slug" && -n "$archive" ]] || die "Usage: clinic-fleet restore <slug> <backup.db.gz>"
    exists "$slug" || die "No such clinic: ${slug}"
    [[ -f "$archive" ]] || die "No such backup: ${archive}"

    local db safety
    db="$(clinic_dir "$slug")/data/clinic.db"

    warn "This replaces ${slug}'s live database with ${archive}."
    read -rp "Type the clinic slug to confirm: " confirm
    [[ "$confirm" == "$slug" ]] || die "Aborted."

    systemctl stop "clinic-bot@${slug}" 2>/dev/null || true

    # Always keep an escape hatch from the restore itself.
    if [[ -f "$db" ]]; then
        safety="${db}.pre-restore-$(date +%Y%m%d-%H%M%S)"
        cp "$db" "$safety"
        ok "Current database preserved at ${safety}"
    fi

    gunzip -c "$archive" >"$db"
    chown "${APP_USER}:${APP_USER}" "$db"

    sqlite3 "$db" "PRAGMA integrity_check;" | grep -q '^ok$' || die "Restored file failed its integrity check."

    systemctl start "clinic-bot@${slug}"
    ok "Restored ${slug}."
}

# ---------------------------------------------------------------------------
cmd_deploy() {
    need_root
    bold "Deploying latest code to every clinic"

    git -C "$APP_DIR" fetch --depth 1 origin main
    git -C "$APP_DIR" reset --hard origin/main
    "${APP_DIR}/.venv/bin/python" -m pip install -e "$APP_DIR" --quiet

    install -m 644 "${APP_DIR}/deploy/clinic-bot@.service" /etc/systemd/system/
    install -m 644 "${APP_DIR}/deploy/clinic-bot.target" /etc/systemd/system/
    systemctl daemon-reload

    # Restart one clinic at a time so a bad release is caught before it takes
    # down all 50.
    local failed=0
    for slug in $(all_slugs); do
        systemctl restart "clinic-bot@${slug}"
        sleep 2
        local port; port="$(clinic_port "$slug")"
        if curl -fsS --max-time 5 "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
            ok "${slug}"
        else
            warn "${slug} did not come back healthy — check: clinic-fleet logs ${slug}"
            failed=$((failed + 1))
        fi
    done

    if [[ "$failed" -eq 0 ]]; then
        ok "Deploy complete, all clinics healthy."
    else
        die "${failed} clinic(s) unhealthy after deploy."
    fi
}

# ---------------------------------------------------------------------------
cmd_health() {
    local port bad=0
    for slug in $(all_slugs); do
        port="$(clinic_port "$slug")"
        if curl -fsS --max-time 3 "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
            ok "$slug"
        else
            warn "$slug UNHEALTHY"
            bad=$((bad + 1))
        fi
    done
    if [[ "$bad" -ne 0 ]]; then
        exit 1
    fi
}

usage() {
    cat <<'EOF'
clinic-fleet — manage many clinic bots on one server

  add <slug>                 Create and wire up a new clinic
  remove <slug>              Stop and archive a clinic
  list                       Show every clinic, its port, state and webhook URL
  start|stop|restart <slug|all>
  logs <slug>                Follow one clinic's logs
  health                     Check every clinic's /health endpoint
  backup [slug|all]          Verified SQLite snapshot (default: all)
  restore <slug> <file.gz>   Restore one clinic from a backup
  deploy                     Pull latest main, reinstall, restart fleet one by one

Configuration: /opt/clinic-bot/fleet.conf  (DOMAIN=...)
EOF
}

case "${1:-}" in
    add)      shift; cmd_add "$@" ;;
    remove)   shift; cmd_remove "$@" ;;
    list|ls)  shift; cmd_list "$@" ;;
    start|stop|restart) action="$1"; shift; cmd_service "$action" "$@" ;;
    logs)     shift; cmd_logs "$@" ;;
    backup)   shift; cmd_backup "$@" ;;
    restore)  shift; cmd_restore "$@" ;;
    deploy)   shift; cmd_deploy "$@" ;;
    health)   shift; cmd_health "$@" ;;
    ""|-h|--help|help) usage ;;
    *)        die "Unknown command '$1'. Try: clinic-fleet help" ;;
esac
