"""UPI QR generation.

Rendered locally with `qrcode` — no third-party QR service, so the clinic's VPA
and the patient's booking reference never leave this server.

Meta fetches image messages by URL, so QR files are written to disk and served by
our own FastAPI app at /qr/{ref}.png.
"""

from __future__ import annotations

import io
import re
from pathlib import Path

import qrcode
from qrcode.constants import ERROR_CORRECT_M

from clinic_bot.clinic_config import ClinicConfig
from clinic_bot.payments.upi import build_upi_uri

QR_DIR = Path("data/qrcodes")

#: Booking refs are generated by us, but this guards the filesystem path anyway.
_SAFE_REF = re.compile(r"^[A-Z0-9\-]{3,32}$")


class InvalidRefError(ValueError):
    pass


def _validate_ref(ref: str) -> str:
    if not _SAFE_REF.match(ref):
        raise InvalidRefError(f"unsafe booking ref for a filename: {ref!r}")
    return ref


def render_qr_png(data: str, *, box_size: int = 10, border: int = 3) -> bytes:
    qr = qrcode.QRCode(
        version=None,
        error_correction=ERROR_CORRECT_M,
        box_size=box_size,
        border=border,
    )
    qr.add_data(data)
    qr.make(fit=True)
    image = qr.make_image(fill_color="black", back_color="white")
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


def qr_path(ref: str) -> Path:
    return QR_DIR / f"{_validate_ref(ref)}.png"


def ensure_qr(cfg: ClinicConfig, *, ref: str, amount: int | None = None) -> Path:
    """Write (or reuse) the QR PNG for a booking and return its path."""
    path = qr_path(ref)
    if path.exists() and path.stat().st_size > 0:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    uri = build_upi_uri(cfg, ref=ref, amount=amount)
    path.write_bytes(render_qr_png(uri))
    return path


def qr_url(base_url: str, ref: str) -> str:
    return f"{base_url.rstrip('/')}/qr/{_validate_ref(ref)}.png"


def pay_url(base_url: str, ref: str) -> str:
    return f"{base_url.rstrip('/')}/pay/{_validate_ref(ref)}"
